# Stage 1: Build the Angular app
FROM node:16-alpine as build

WORKDIR /src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the Angular app
RUN npm run build

# Stage 2: Create a minimal image to serve the Angular app
FROM nginx:alpine

# Copy the compiled artifacts from the build stage
COPY --from=build /src/app/dist /usr/share/nginx/html

# Expose the default port used by Nginx
EXPOSE 4200

# Start Nginx to serve the Angular app
CMD ["nginx", "-g", "daemon off;"]