name: CI/CD with Auto-Tagging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository again
        uses: actions/checkout@v2

      - name: Move into the repository directory
        run: cd essa-project

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Tag the commit
        run: git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

      - name: Push tags to the repository
        run: git push origin --tags
