name: CI/CD with Auto-Tagging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository again
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get latest tag
        id: get_latest_tag
        run: echo ::set-output name=latest_tag::$(git describe --abbrev=0 --tags || echo "v0.0.0")

      - name: Bump version
        id: bump_version
        run: echo ::set-output name=new_version::$(node -e "console.log('${{ steps.get_latest_tag.outputs.latest_tag }}'.replace(/^v/, '').split('.').map(Number).slice(0, 2).concat(Number('${{ steps.get_latest_tag.outputs.latest_tag }}'.replace(/^v/, '').split('.')[2]) + 1).join('.'))")

      - name: Check if tag exists
        id: check_tag
        run: git tag -l ${{ steps.bump_version.outputs.new_version }}

      - name: Tag the commit (if tag doesn't exist)
        run: |
          if [ -z "${{ steps.check_tag.outputs.check_tag }}" ]; then
            git tag ${{ steps.bump_version.outputs.new_version }}
          else
            echo "Tag already exists, skipping."
          fi

      - name: Push tags to the repository
        run: git push origin --tags
